### PR TITLE
fix: read correct property name in PUT tenant handler

### LINKED ISSUE #966: PUT tenant handler reads wrong property name for maxResolution
In the PUT handler for tenants (`src/http/routes/admin/tenants.ts`), the condition correctly checks `features?.imageTransformation?.maxResolution` but the assignment reads `features?.imageTransformation?.image_transformation_max_resolution` -- which is the DB column name, not the request body property.

Since the request schema defines the field as `maxResolution` (camelCase), the snake_case property is always `undefined`, so the max resolution setting is silently dropped on PUT.

The PATCH handler in the same file handles this correctly, reading `maxResolution` consistently.

### PR DESCRIPTION
**Pull request by oniani1**
Fixes #966

The PUT handler for tenants checks `features?.imageTransformation?.maxResolution` in the condition but then reads `features?.imageTransformation?.image_transformation_max_resolution` in the assignment. The snake_case name is the DB column, not the request body property, so it's always `undefined`.

The PATCH handler right above does this correctly -- reads `maxResolution` in both places. This just aligns the PUT handler with the same pattern.

### CODE REVIEW

File: src/internal/database/migrations/migrate.ts [hunk 1]
```diff
@@ -806,7 +806,7 @@ async function doesSchemaExists(client: BasicPgClient, schemaName: string) {
       WHERE schema_name = ${schemaName}
   );`)
 
-  return result.rows.length > 0 && result.rows[0].exists === 'true'
+  return result.rows.length > 0 && result.rows[0].exists
```
Comment (fenos) [inline src/internal/database/migrations/migrate.ts:809]: Not sure why this change was committed?

Comment (fenos) [reply src/internal/database/migrations/migrate.ts:809]: Ah got it, is a change from another PR.
