### PR TITLE
fix: support s3 chunked upload

### LINKED ISSUE #577: Golang aws sdk v2 cannot upload to supabase storage
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
I got issue while using golang aws sdk v2 (github.com/aws/aws-sdk-go-v2) to integrate with supabase storage. The [document](https://supabase.com/docs/guides/storage/debugging/error-codes) said I should check again the error `SignatureDoesNotMatch` but I set access key id / access secret key / region that are all correct
```
operation error S3: PutObject, https response error StatusCode: 403, RequestID: , HostID: , api error SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## System information
- Version of Go go 1.22.0

### PR DESCRIPTION
**Pull request by fenos**
## What kind of change does this PR introduce?

Bug fix / Feature

## What is the current behavior?

Not supporting chunked uploads, producing a corrupted file

## What is the new behavior?

Support S3 chunked upload:

- https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html
- https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-auth-using-authorization-header.html

## Additional context

Fixes #577

### CODE REVIEW

File: src/storage/protocols/s3/signature-v4.ts [hunk 1]
```diff
@@ -267,6 +278,45 @@ export class SignatureV4 {
...
+      algorithm,
+      clientSignature.longDate,
+      scope,
+      prevSignature,
+      emptyHash,
+      chunkHash,
+    ].join('\n')
+
+    // 4) HMAC it with the derived key and compare
+    const expected = crypto.createHmac('sha256', signingKey).update(stringToSign).digest('hex')
```
Comment (itslenny) [inline src/storage/protocols/s3/signature-v4.ts]: Can this use the existing `this.hmac()` helper function?

**Review by itslenny — APPROVED** [review]
